name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🧰 Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: 🛠️ Install dependencies 
        run: |
          chmod +x ./scripts/install.sh
          make install

      - name: 🔨 Build & Test
        run: |
          make prod
          go test -v ./...

      - name: ✅ Check if binary exists
        run: |
          mkdir -p bin
          if ls bin/* 1> /dev/null 2>&1; then
            echo "✅ Binary found in bin/"
          else
            echo "❌ No binary found in bin/"
            exit 1
          fi

      - name: 🗂 List contents of bin directory
        run: ls -lh bin/

  notify-on-failure:
    needs: build
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: ❌ Notify via GitHub issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "❌ CI Failed in Go Workflow"
          content-file: .github/workflow_failure_message.md
          labels: |
            ci
            failure
